[project]
name = "bancario"
version = "0.1.0"
description = "Simulador de ATM"
requires-python = ">=3.13"
dependencies = [
    "faker>=40.1.0",
    "freesimplegui>=5.2.0.post1",
]

[dependency-groups]
dev = [
    "black>=25.12.0",
    "flake8>=7.3.0",
    "isort>=7.0.0",
]
